### ISSUE TITLE
QGIS Mapserver can return incomplete list of features in GetFeatureInfo request

### ISSUE THREAD

**Issue by marcel-dancak** [gislab-npo/gislab#339]
When searching features (GetFeatureInfo request) with FILTER parameter but without BBOX, most outside features may be omitted in mapserver's response. It is caused by rounding extents during transformation between different projections (when project's crs differ from layer's crs).

**Comment by marcel-dancak** [comment]
Patch for QGIS 2.2: https://github.com/marcel-dancak/QGIS/commit/b0b1f4d94fea142db3057e99e0b4efc4de166a69

**Comment by imincik** [comment]
@marcel-dancak, thank you very much for this quick patch. Please do not forget to send it to upstream.

**Comment by imincik** [comment]
Uploaded to ppa:imincik/gis-dev .

**Comment by imincik** [comment]
Uploaded to ppa:imincik/gis .

**Comment by imincik** [comment]
@marcel-dancak, reassigning to you. Please send patch to upstream.

**Comment by imincik** [comment]
@marcel-dancak, what is the state of this patch in upstream ? Was it accepted in QGIS 2.8 ?

**Comment by imincik** [comment]
@marcel-dancak, would you please take a care of this patch and close this ticket once it is confirmed in upstream ?
