### ISSUE TITLE
GDAL GRASS 7 plugin

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#369]
We need to compile GDAL plugin for GRASS 7.

See:
https://pvanb.wordpress.com/2015/12/05/compiling-the-gdal-grass-plugin-for-grass-7/

**Comment by landam** [comment]
Here is patch for GDAL 1.10: http://geo102.fsv.cvut.cz/~landa/tmp/gdal-grass-1-10.diff

**Comment by landam** [comment]
Closing as wontfix. Already solved in ubuntu-xenial-dev branch.
