### ISSUE TITLE
First GIS.lab client login takes very long time

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#376]
First GIS.lab client login takes very long time because of some problem with LDAP connection.

**Comment by mpastor** [comment]
I think that this issue isn't relevant with bug #412. I have made a lot of tests with login, but this message (Can't contact LDAP server) has appeared only in one case.

**Comment by mpastor** [comment]
With LXDE the problem disapear.
But:
- first login to LXDE - ok
- logout
- login to GIS.lab (xfce) - too long
- logout
- login again to GIS.lab - ok

**Comment by mpastor** [comment]
@imincik please try with this mount options on client:
```
server.gis.lab:/storage/home          /mnt/home         nfs   defaults,rsize=8192,wsize=8192   0   0
server.gis.lab:/storage/repository    /mnt/repository   nfs   defaults,rsize=8192,wsize=8192   0   0
server.gis.lab:/storage/publish       /mnt/publish      nfs   defaults,rsize=8192,wsize=8192   0   0
server.gis.lab:/storage/barrel        /mnt/barrel       nfs   defaults,rsize=8192,wsize=8192   0   0
```

**Comment by imincik** [comment]
8192 is very low value, can't use it as default.My current negotiated value in VirtualBox is 131072.

**Comment by imincik** [comment]
Can somebody try to paste here the output from following command (on client machine) if problem occurs:

 cat /proc/mounts | grep /storage/home

**Comment by landam** [comment]
This issue seems to be not valid any more for master (xenial based).
