### ISSUE TITLE
Ubuntu version upgrade

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#388]
Upgrade Ubuntu version to the next one running on systemd by default and XFCE 4.12.

See:
- https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files
- http://packetpushers.net/udev/  - great article on network devices configuration using udev

Notes:
- upgrade providers: gislab-unit, aws
- rebuild 'busybox' package with our server filter patch - https://github.com/imincik/gis-lab/blob/master/system/roles/client-desktop/doc/patch/server-filter.patch
- use systemd-nspawn instead of plain chroot (https://wiki.archlinux.org/index.php/Systemd-nspawn, http://www.linux.it/~ema/2015/10/07/systemd-is-your-friend/, https://copyninja.info/blog/taming_systemd_nsapwn.html)
- use systemd-nspawnd bind to mount /var/cache/apt and others to chroot (systemd-nspawn -D . –bind /usr/portage)
- use systemd-networkd
- use systemd.link for network devices naming - http://www.freedesktop.org/software/systemd/man/systemd.link.html
- use systemd-resolved
- porting of our custom shutdown and reboot scripts (client-desktop/files/static/bin/reboot|poweroff)
- update packages installed in Python virtualenvs
- use packages from Ubuntu repositories if possible, rather than from pip (gunicorn, serf, ...) 
- update desktop themes and icons
- central logging using systemd-journald + syslog
- adding support for IP address lease renewal for GIS.lab Desktop (#433)
- use syslog logging for Nginx web server (available in latest nginx version)
- install latest kernel for Desktop client - remove code installing 3.8 due to VBox additions incompatibility
- Python 2.7 support for GIS.lab Web and other tools
- update of gislab-client-shell and gislab-client-image tools
- adding desktop tests which will benefit from booting desktop environment with nspawn
- LightDM hooks update
- support for fallback static IP address when there is no DHCP in network - could it be possible to set multiple network configurations for  the same network device ? - https://coreos.com/blog/intro-to-systemd-networkd/ or try to set some service which will use 'Systemd Conditions'
# Examples
### Example SystemD configuration for Gunicorn service

gunicorn.service:

```
[Unit]
Description=gunicorn daemon
Requires=gunicorn.socket
After=network.target

[Service]
PIDFile=/run/gunicorn/pid
User=someuser
Group=someuser
WorkingDirectory=/home/someuser
ExecStart=/home/someuser/gunicorn/bin/gunicorn --pid /run/gunicorn/pid test:app
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

gunicorn.socket:

```
[Unit]
Description=gunicorn socket

[Socket]
ListenStream=/run/gunicorn/socket
ListenStream=0.0.0.0:9000
ListenStream=[::]:8000

[Install]
WantedBy=sockets.target
```

tmpfiles.d/gunicorn.conf:

```
d /run/gunicorn 0755 someuser someuser -
```

**Comment by mpastor** [comment]
## Server installation analyze ##

### installation-setup ###

- change OS version

### basic-configuration ###

- network configuration
  - disable old style network configuration - remove /etc/network/interfaces
  - remove dhcp client configuration - /etc/dhcp/dhclient.conf
  - don't install GIS.lab network hook - /etc/network/if-up.d/001gislab
  - configure systemd-networkd
  - enable systemd-networkd service

- apt configuration

### account-users ###

- nothing to do

### service-syslog ###

???

### service-logcheck ###

???

### service-time ###

- disable systemd-timesyncd.service

### service-dns ###

- depends on network configuration
  - don't install resolvconf
  - install systemd-resolved configuration /etc/systemd/resolved.conf
  - enable and start systemd-resolved service
  - update /etc/resolv.conf (should be symlink to /var/run/systemd/resolve/resolv.conf)

### service-ldap ###

- install packages: auth-client-config libpam-ldap

- database has changed from HDB to MDB

- remove all indexes and readd them

- ldapscripts fix is not required

- apply new ldapscripts fix

### service-mail ###

- nothing to do

### service-dhcp ###

- modify apparmor configuration:
  - allow access to '/run/systemd/resolve/resolv.conf'

- solve the problem with network interface

### service-default-web ###

- nothing to do

### service-files ###

- nothing to do

### service-chat ###

- nothing to do

### service-database ###

- package 'pgtune' has been removed

- change postgresql version (package, configuration files...)

- install X509 certificate

- change configuration directive: unix_socket_directory -> unix_socket_directories

### service-mapserver ###

- replace upstart script with systemd unit

### service-load-balancer ###

- rewrite upstart script to systemd unit file

### service-statistics ###

- nothing to do

### service-cluster ###

- replace upstart script with systemd unit file

- solve the problem with network interface

### service-connection-forwarding ###

- replace upstart script with systemd unit file

- solve the problem with network interface

### service-vpn ###

- install packages: 'easy-rsa'

- easy-rsa tools have been moved to /usr/share/easy-rsa

- fix ease-rsa tools

- size of keys has been changed from 1024 to 2048

- modify 'vars'

- name of the auth plugin has been changed from 'openvpn-auth-pam.so' to 'openvpn-plugin-auth-pam.so'

### client-web ###

- install packages: virtualenv

- replace upstart script with systemd unit file

### client-mobile ###

???

### account-admin ###

- nothing to do

### example-data ###

- nothing to do

### installation-done ###

- nothing to do

**Comment by mpastor** [comment]
## Client installation analyze ##

### client-desktop ###

- solve problem with packages:
 
- rewrite all chroot operations to systemd nspawn
  - systemctl doesn't work with nspawn

- set appropriate kernel and headers packages

- NTP is configured via /etc/default/ntpdate, but ntpdate is not installed

- configure NTP via systemd timesyncd service

- syslog ???

- fix lightdm (greeter, themes, menu)

- disabling useless services - upstart scripts, systemd

- fix reboot, shutdown, poweroff...

- fix GIS.lab client desktop customizations

- replace serf upstart scripts with systemd unit file
    - how to deal with serf join
    - command substitution not working (find network interface)

- replace Xvfb upstart script with systemd unit

- update initramfs sctipts
    - update hooks and scripts
    - udhcpc
        - apply patch
        - network interface name is unpredictable,
          so maybe we should use original method
          of acquiring an IP address

- replace upstart gislab client script with systemd unit

#### provider-default ####

- replace http boot upstart script with systemd unit file (server)

#### provider-aws ####

- nothing to do

**Comment by landam** [comment]
See ubuntu-xenial-dev branch for progress.

**Comment by landam** [comment]
Implemented in ubuntu-xenial-dev branch.
