### ISSUE TITLE
GIS.lab client - it is impossible to continue login process once invalid user name is entered

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#402]
It is impossible to continue login process once invalid user name is entered in LightDM. Client machine must be restarted in order to enter other user name.

Here is a patch for newer LightDM version, which needs to be backported to version installed in GIS.lab.

``` c
Index: lightdm-gtk-greeter-1.3.1/src/lightdm-gtk-greeter.c
===================================================================
--- lightdm-gtk-greeter-1.3.1.orig/src/lightdm-gtk-greeter.c
+++ lightdm-gtk-greeter-1.3.1/src/lightdm-gtk-greeter.c
@@ -204,12 +204,12 @@ start_authentication (const gchar *usern
     }
     g_free (data);

-    if (strcmp (username, "*other") == 0)
+    if (g_strcmp0 (username, "*other") == 0)
     {
         gtk_widget_show (GTK_WIDGET (cancel_button));
         lightdm_greeter_authenticate (greeter, NULL);
     }
-    else if (strcmp (username, "*guest") == 0)
+    else if (g_strcmp0 (username, "*guest") == 0)
     {
         lightdm_greeter_authenticate_as_guest (greeter);
     }
```

**Comment by imincik** [comment]
Possible workaround is to press CTRL-ALT-F1 to switch to text console, login as super user and run '$sudo service lightdm restart'

**Comment by landam** [comment]
I built patched `lightdm-gtk-greeter` package (1) and tested. It's not behaving well:

 1) enter non-existing login
 2) enter some password
 3) enter password again
 4) click on 'cancel'

Then the LightDM freezes.

I would suggest to close this issue as 'wontfix' and wait for major upgrade to Ubuntu 16.04.

(1) https://launchpad.net/~landa-martin/+archive/ubuntu/gislab-testing/+packages

**Comment by landam** [comment]
Already solved in ubuntu-xenial-dev branch.
