### ISSUE TITLE
Change host name on GIS.lab server to 'server-$GISLAB_UNIQUE_ID'

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#423]
Change host name on GIS.lab server to 'server-$GISLAB_UNIQUE_ID'.

* add DNS alias 'server' pointing to GIS.lab server.
* how to change prompt ?

**Comment by mpastor** [comment]
It's not possible to set hostname to e.g. 'gislab_vagrant', because it contains not allowed character '_'.
Valid characters for hostname are ASCII letters (a-z), numbers (0-9) and hyphen (-).

**Comment by imincik** [comment]
After reconsidering this, I am closing this ticker without implementation
