### ISSUE TITLE
Consolidation of software sources

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#466]
The goal of this task is to install as much as possible software from Ubuntu repository. Advantages of this approach are better caching and reliability.

Proposed packages:
- serf - the most important one, currently in Debian Unstable
- Python and JS software
- consider installation of JOSM, which is third party repository which can be potentially broken

**Comment by landam** [comment]
Closed as wontfixed (some of issue already solved in ubuntu-xenial-dev branch).
