### ISSUE TITLE
GIS.lab server: PostgreSQL performace tuning

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#475]
pgtune script is not longer supported and also usable for PostgreSQL 9.4. We need to find a new way how to auto-tune PostgreSQL server.
Also note, that PostgreSQL 9.4 and later use a different shared memory mechanism, so kernel settings will usually not have to be adjusted there.

At least, we can autotune 'shared_buffers' according server RAM.

See:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761179
- https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server

**Comment by landam** [comment]
See: https://github.com/imincik/ansible-postgresql_tune
