### ISSUE TITLE
gislab-unit-iso.sh: replace mkisofs by genisoimage

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#484]
Debian replaced `mkisofs` by `genisoimage` some time ago. It seems that the both commands behave the same and can be substituted. So probably the `gislab-unit-iso.sh` could use `genisoimage` automatically when `mkisofs` is not available.

**Comment by imincik** [comment]
Please try if genisoimage is working on Debian unstable. If yes, we can use it. If I remember correctly, I had some problem when using it in the past on Ubuntu.

**Comment by landam** [comment]
I have tried today and it worked, the iso image was created.

**Comment by imincik** [comment]
Fine, we can use something like
```
$ mkisofs .... || genisoimage ....
```

**Comment by landam** [comment]
Tested locally 

```
-mkisofs -D -r \
+mkisofs || genisoimage -D -r \
 ```

works as expected.

**Comment by imincik** [comment]
OK, can you apply this change ?
