### ISSUE TITLE
ansible_ssh_user is undefined

### ISSUE THREAD

**Issue by abusquets** [gislab-npo/gislab#485]
At the end of vagrant up I have this error.

TASK [Create shared development directory] *************************************
fatal: [gislab-web]: FAILED! => {"failed": true, "msg": "ERROR! 'ansible_ssh_user' is undefined"}

**Comment by imincik** [comment]
Hi @abusquets, thanks for bug report.
I believe the problem you are reporting belongs to [GIS.lab Web](https://github.com/gislab-npo/gislab-web) repository. 

Moving to https://github.com/gislab-npo/gislab-web/issues/25
