### ISSUE TITLE
Bottom bar doesn't adapt to the size of desktop window

### ISSUE THREAD

**Issue by lfurtkevicova** [gislab-npo/gislab#486]
Bottom bar doesn't react to maximize button. It is still on the same part of window, see PrtSc:

![maximize](https://cloud.githubusercontent.com/assets/13394357/13076944/02e65108-d4b6-11e5-8119-3283dea154ca.png)

**Comment by imincik** [comment]
@lfurtkevicova, thanks for reporting. It is behaviour of Conky which doesn't expect on-the-fly screen resizing. For me it is minor issue, but patches are welcome. But I suggest to wait until new Ubuntu version to see if the problem will persist.

**Comment by landam** [comment]
Seems to be solved by updating to Xenial.
