### ISSUE TITLE
xenial-dev branch testing

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#493]
Hi, I started testing xenial-dev branch. The command

```
vagrant up
```

(having version 1.8.1) fails quite recently with

```
==> gislab_vagrant: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:



Stderr from the command:

sudo: unable to resolve host ubuntu-xenial
mesg: ttyname failed: Inappropriate ioctl for device
```

**Comment by imincik** [comment]
On May 1, 2016 12:20 AM, "Martin Landa" <notifications@github.com> wrote:
>
> Hi, I started testing xenial-dev branch. The command
>
> vagrant up
>
> (having version 1.8.1) fails quite recently with
>
> ==> gislab_vagrant: Configuring and enabling network interfaces...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
>
> /sbin/ifdown eth1 2> /dev/null
>
> Stdout from the command:
>
>
>
> Stderr from the command:
>
> sudo: unable to resolve host ubuntu-xenial
> mesg: ttyname failed: Inappropriate ioctl for device
>

Hi Martin,
This issue is reported on Ubuntu Launchpad a this is the reason I have
created our own temporary Vagrant box as the work around. The problem was
probably not fixed until now.

I am not able to provide the details, but when you search earlier
discussions, you will find the link to download fixed box.

Sorry for that.

**Comment by landam** [comment]
@imincik you are right,

with

```
vagrant box remove xenial-canonical
vagrant box add -f xenial-canonical http://gislab-download.s3.amazonaws.com/xenial-server-cloudimg-amd64-vagrant~imincik3.box
```

it works

```
vagrant up
...
PLAY RECAP *********************************************************************
gislab_vagrant             : ok=250  changed=198  unreachable=0    failed=0   
```

**Comment by landam** [comment]
I changed Vagrantfile to use working image in 4d821f8. This should be change once the official image will be fixed.

**Comment by landam** [comment]
`vagrant up` with `http://gislab-download.s3.amazonaws.com/xenial-server-cloudimg-amd64-vagrant~imincik3.box` image work. But reloading machine by `vagrant reload` fails with

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1

Stdout from the command:

Failed to bring up eth1.


Stderr from the command:

tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
mesg: ttyname failed: Inappropriate ioctl for device
RTNETLINK answers: File exists
```

**Comment by landam** [comment]
Attempt to restart machine by `vagrant halt && vagrant up` has the same effect.

**Comment by imincik** [comment]
Hi @landam , please be  aware tahe "xenial-server-cloudimg-amd64-vagrant~imincik3.box" box is very outdated. It was created in even before 16.04 beta was released.

**Comment by landam** [comment]
For record: related issue on Launchpad - https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1546108

**Comment by landam** [comment]
And https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1538547

**Comment by imincik** [comment]
@landam , in work we have just moved Hashicorp Vagrant boxes.

Please try this one:
* https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04

Please note that you need only this configuration in Vagrant file (no config.vm.box_url):
```
box = "bento/ubuntu-16.04"
```

**Comment by landam** [comment]
Thanks, anyway result seems to be the same:

```
==> gislab_vagrant: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
    gislab_vagrant: Box Provider: virtualbox
    gislab_vagrant: Box Version: >= 0
==> gislab_vagrant: Loading metadata for box 'bento/ubuntu-16.04'
    gislab_vagrant: URL: https://atlas.hashicorp.com/bento/ubuntu-16.04
==> gislab_vagrant: Adding box 'bento/ubuntu-16.04' (v2.2.7) for provider: virtualbox
    gislab_vagrant: Downloading: https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04/versions/2.2.7/providers/virtualbox.box
==> gislab_vagrant: Successfully added box 'bento/ubuntu-16.04' (v2.2.7) for 'virtualbox'!
==> gislab_vagrant: Importing base box 'bento/ubuntu-16.04'...
==> gislab_vagrant: Matching MAC address for NAT networking...
==> gislab_vagrant: Checking if box 'bento/ubuntu-16.04' is up to date...
...
==> gislab_vagrant: Machine booted and ready!
==> gislab_vagrant: Checking for guest additions in VM...
==> gislab_vagrant: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:



Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
```

Vagrant version 1.8.1

**Comment by landam** [comment]
FYI, the reported issue related to private network has been fixed in vagrant recently, https://github.com/mitchellh/vagrant/issues/7288. I tested vagrant from git master and I can confirm it. 

@imincik @mpastor Probably we could require Vagrant 1.8.2 in our playbooks

**Comment by imincik** [comment]
Great. Please upgrade required Vagrant version.

**Comment by landam** [comment]
Done in 6920449, the required version should be changed to >=1.8.2 when the version will be released.
