### ISSUE TITLE
xenial iso image refuses to boot

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#495]
I tried to create GIS.lab ISO image based on Ubuntu 16.04 Server ISO. After installation the unit refuses to boot, the result is a black screen and nothing happens. I was able to install plain OS. There were few differences, except of Apt proxy server the installer asked me also for:
- The installer has detected that the following disks have mounted partitions: /dev/sda... Umount partitions that are use? I chose YES (NO doesn't make sense at all here), and
- Install the GRUB boot loader on hard disk. Device to boot loader installation: I chose /dev/sda

The installer based on Ubuntu 12.04 works as expected (same unit, same usb flash disc, same procedure). The system boots normally. 

I tried to create bootable USB disk based on original ubuntu-server-16.04 ISO. The OS after installation booted normally, so it must be something related to GIS.lab ISO creation process. Is xenial installer expected to work?

See also related discussion at https://lists.osgeo.org/pipermail/gis.lab/2016-June/000130.html

**Comment by mpastor** [comment]
could you try to boot with "nomodeset" kernel parameter?
after the initial POST test press "escape" key (more time) to enter GRUB menu. move cursor on "*Ubuntu" and press "e" key. find line with something like:
```
linux /vmlinuz-4.4... root=/dev/... ro quite...
```
and append "nomodeset" to the end of this line and press "f10" key.
eventually you can press "escape" key during boot.

**Comment by landam** [comment]
@mpastor thanks for tip, I tried that but it had no effect (silent black screen)

**Comment by landam** [comment]
Anyway, the system boots. I discovered that when I choosing "Advanced options for Ubuntu" -> Ubuntu (recovery mode)". So, something related to video card? Strangely I don't have this issue when installing OS from original Ubuntu ISO.

**Comment by landam** [comment]
Regardless a black screen I am able to login via ssh normally. So the OS is running.

**Comment by mpastor** [comment]
try to remove "splash" parameter and add "nomodeset".

**Comment by mpastor** [comment]
if it still did not work, try add another parameter "i915.modeset=0".

**Comment by landam** [comment]
@mpastor none of them helped, but I discovered that removing `$vt_handoff` helps. Do you know how to modify `providers/gislab-unit/iso` to remove this parameter from GRUB setparams? Ideally `splash` parameter should be also removed.

**Comment by landam** [comment]
Regarding "The installer has detected that the following disks have mounted partitions", see also related https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1347726
