### ISSUE TITLE
xenial: network devices names

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#497]
After GIS.lab initialization (see #496) I run 

```
ansible ... system/gislab.yml
```

which failed with 

```
TASK [basic-configuration : Activate GIS.lab network IP address if not received from provider] ***
fatal: [gislab-unit-cvut]: FAILED! => {"changed": true, "cmd": ["ip", "addr", "add", "192.168.17.5/24", "dev", "eth0"], "delta": "0:00:00.004454", "end": "2016-06-05 14:19:02.564178", "failed": true, "rc": 1, "start": "2016-06-05 14:19:02.559724", "stderr": "Cannot find device \"eth0\"", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by landam** [comment]
@mpastor I guees that the settings should be set from `eth0` to `eno1`?

**Comment by landam** [comment]
The issue with network device should be fixed by 6fe4b95.

**Comment by landam** [comment]
The rest of roles finishes successfully.

```
PLAY RECAP *********************************************************************
gislab-unit-cvut           : ok=347  changed=285  unreachable=0    failed=0   
```

**Comment by landam** [comment]
Shouldn't be GISLAB_SERVER_NETWORK_DEVICE in Vagrantfile changed from eth1 to eno2? BTW, there are still references in the code to eth0:

```
 providers/gislab-unit/iso/gislab.seed.template:d-i netcfg/choose_interface select eth0
providers/gislab-unit/templates/network/fix-hardware-unit-hang.j2:ethtool -K eth0 tso off
system/roles/client-desktop/templates/initramfs-tools/scripts/init-premount/udhcp.j2:iface=eth0
system/roles/client-desktop/templates/initramfs-tools/scripts/init-premount/udhcp.j2:        # Make a DHCP request for interface eth0
system/roles/client-desktop/templates/desktop/conky/conky.conf.j2:${color0}ETH0 ${color1}${downspeed eth0}:${upspeed eth0}
system/group_vars/all:# 'eth0' and setting default gateway via 'eth1' device.
system/group_vars/all:# Removing original default gateway: ip route del default via 10.0.2.2 dev eth0
```

**Comment by landam** [comment]
See https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

**Comment by landam** [comment]
In summary:

* change eth0 to eno1 in all files
* change eth1 to eno2 in all files

@imincik @mpastor Make sense to you?

**Comment by imincik** [comment]
@landam , network devices names can vary in different systems. It is very complicated, but I have some ideas.

For sure, the network names should be replaced by ansible network device variables, they shouldn't be hardcoded.

In "client-desktop" we can even implement predictable network names, because we have full control on that system, but with server we must probably finish with some better solution.

**Comment by landam** [comment]
@imincik , can you provide some details about your idea? Thanks!

**Comment by landam** [comment]
All issues seems to be solved.
