### ISSUE TITLE
xenial: autocompleation of gislab command doesn't work

### ISSUE THREAD

**Issue by landam** [gislab-npo/gislab#498]
The gislab commands like eg. `gislab-machines` is not possible to autocomplete

```
sudo gislab-
```

pressing TAB doesn't offer any choices. Even the command `gislab-machines` is possible to launch and it's found by `which` command:

```
which gislab-machines
/opt/gislab/admin/gislab-machines
```

**Comment by landam** [comment]
Fixed by acac8b9

**Comment by landam** [comment]
There is still issue with `gislab-cluster` command:

```
which gislab-cluster
[nothing found]
```

The other commands are found and can be autocompleted.

```
which gislab-adduser
/opt/gislab/admin/gislab-adduser
```

**Comment by landam** [comment]
Strangely the file is located in /usr/local/bin:

```
locate gislab-cluster
/usr/local/bin/gislab-cluster
```

**Comment by imincik** [comment]
/usr/local/bin/gislab-cluster is just symlink to "serf" binary. Is serf installed ?

**Comment by landam** [comment]
yes, serf is installed. 

```
udo serf --version
Serf v0.6.4
Agent Protocol: 4 (Understands back to: 2)
```
