### ISSUE TITLE
DHCP service update

### ISSUE THREAD

**Issue by imincik** [gislab-npo/gislab#505]
## Use cases
* No DHCP server in network: GIS.lab DHCP: yes, LAN: static IP, WAN: static IP, connection forwarding: yes
* DHCP present in network: GIS.lab DHCP: no, LAN: via DHCP, WAN: no, connection forwarding: no
* Vagrant: GIS.lab DHCP: yes, LAN: static IP, WAN: static IP, connection forwarding: yes, Note: laptop connected via WiFi, but GIS.lab nework binded to eth0

# Tasks
## DHCP service configuration
* DHCP service must be always turned off by default
* DHCP service will be configured to work in range 192.168.5.0/255 by default

## Default network configuration (server)
Changed network configuration in /etc/network/interfaces
* one IP address with DHCP client
* other use case with two static IP addresses commented out

## Removal of DNS service
* DNS service should be removed from server and substituted by single "server.gis.lab" record dynamically written to /etc/hosts file on client machines

## Config cleanup
Following configuration variables should be removed:
* GISLAB_NETWORK
* GISLAB_SERVER_INTEGRATION
* GISLAB_INTEGRATION_FALLBACK

## Other tasks
* update all documentation about networking and client boot process
* remove all no longer needed patches around udhcpc on client machines

**Comment by landam** [comment]
FYI: I have created for development issues a new branch https://github.com/gislab-npo/gislab/tree/dhcp-service-dev

**Comment by landam** [comment]
See 3507cb2c7d541b4c5989649013f55f13c0e16a5f

**Comment by landam** [comment]
I tested two cases bellow:

*    DHCP present in network: GIS.lab DHCP: no, LAN: via DHCP, WAN: no, connection forwarding: no

On third-party DHCP server NEXT_SERVER and FILE options were defined. File `/var/lib/tftpboot/gislab/pxelinux.cfg/default` has been manually changed to reflect Unit IP address. Clients booted and system seems to work.

*    Vagrant: GIS.lab DHCP: yes, LAN: static IP, WAN: static IP, connection forwarding: yes, Note: laptop connected via WiFi, but GIS.lab nework binded to eth0

Vagrant machine created. Then required services have been started:

```
sudo service isc-dhcp-server start
sudo service bind9 start
sudo service gislab-connection-forwarding start
```
Clients booted via PXE. HTTP boot hasn't been tested yet.

**Comment by mpastor** [comment]
It's no more necessary to modify `/var/lib/tftpboot/gislab/pxelinux.cfg/default` configuration file - client will use IP server address from DHCP options acquired from DHCP server.
